[advisories]
ignore = [
    "RUSTSEC-2024-0388",
    "RUSTSEC-2024-0436",
]

# For these categories, just set the lint level directly
unmaintained = "deny"
unsound = "deny"
yanked = "deny"

# Optional: set a global severity threshold
severity-threshold = "low"

[licenses]
allow = ["MIT", "Apache-2.0", "BSD-3-Clause"]
deny = ["GPL-3.0", "AGPL-3.0"]
