[advisories]
ignore = [
    "RUSTSEC-2024-0388",
    "RUSTSEC-2024-0436",
]

# These control what is denied
unmaintained = "all"
unsound = "all"
yanked = "all"

[licenses]
allow = ["MIT", "Apache-2.0", "BSD-3-Clause"]
deny = ["GPL-3.0", "AGPL-3.0"]
