name: Documentation Validation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  link-check:
    name: Check Broken Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check links with lychee
        uses: lycheeverse/lychee-action@v2
        with:
          # Check all markdown files in docs/ and README.md
          args: '--verbose --no-progress --config lychee.toml docs/ README.md'
          # Fail action on broken links
          fail: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Issue From File
        if: failure()
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: 'Broken links detected in documentation'
          content-filepath: ./lychee/out.md
          labels: |
            documentation
            broken-links

  spell-check:
    name: Check Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check spelling with cspell
        uses: streetsidesoftware/cspell-action@v7
        with:
          # Check all files in docs/ and README.md
          files: |
            docs/**/*.md
            README.md
          # Use strict mode - fail on spelling issues
          strict: true
          # Show inline warnings
          inline: warning
          # Use config from .cspell.json
          config: '.cspell.json'

  docs-validation-success:
    name: Documentation Validation Success
    runs-on: ubuntu-latest
    needs: [link-check, spell-check]
    if: always()
    steps:
      - name: Check all jobs
        run: |
          if [[ "${{ needs.link-check.result }}" != "success" || \
                "${{ needs.spell-check.result }}" != "success" ]]; then
            echo "One or more documentation validation jobs failed"
            exit 1
          fi
          echo "All documentation validation jobs passed successfully"
